### ISSUE TITLE
Code for Micropython (Pico Pi)

### ISSUE THREAD

**Issue by JoSteiPi** [JPEWdev/pyhid-usb-relay#4]
Hi there, the pyhid-usb-relay library works great on my raspberry pi in python. Can you give me a pointer on where I could find code required to do the same in MicroPython on my Pico Pi? Many thanks!

**Comment by JPEWdev** [comment]
The relays use a USB HID interface that isn't too complex if you read through the code in this library you might be able to make a MicroPython version pretty easily.... it's would be even easier if MicroPython has an equivalent `usb` library, but I don't know if it does or not
