### ISSUE TITLE
Question rather than Issue regarding multi-channel boards.

### ISSUE THREAD

**Issue by valonvn** [JPEWdev/pyhid-usb-relay#5]
Apologies as I'm sure this isn't the correct method of contact, though GitHub don't offer a contact method anymore.

Simple enough I can see that folks have created programs using the initial repo (not the python version) to interact with boards containing more than one channel, however I'm wondering if the Python version is capable of this?

The example code I've seen simply refers to the relay object via the find function which seems to only be the one, so just want to make sure I can interact with say, a 2-channel board using this repo.

**Comment by valonvn** [comment]
Fair play, yes if it supports 8-channel I see no reason it should struggle there,

Perhaps I'm missing something then but could I trouble you for some example code on interacting with multiple channels?

**Comment by JPEWdev** [comment]
Ya, sorry, the example isn't very good

```python3
import pyhid_usb_relay

my_relay_board = pyhid_usb_relay.find()

# Set relay 1 to "on"
my_relay_board.set_state(1, True)

# Toggle relay 2
my_relay_board.toggle_state(2)

# Set all relays to off
my_relay_board.set_state("all", False)

# Get the state of relay 3
if my_relay_board.get_state(3):
    print("Relay 3 is on!")
```

**Comment by valonvn** [comment]
Ah this is fantastic, very much appreciated!
