### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by ghost** [JPEWdev/pyhid-usb-relay#6]
[deleted]

**Comment by valonvn** [comment]
Resolved, 

My apologies I wasn't aware the process itself would close after setting the state of the relay, simply finding the relay again after the waited time allows me to set it to a new value.

**Comment by JPEWdev** [comment]
I think that is an actual issue, would you mind providing a sample script that reproduces it?

**Comment by valonvn** [comment]
Oh for sure!
I mean the initial post has the example code I used there (t's actually part of a Discord Bot)

`relay = pyhid_usb_relay.find()
            relay.set_state(1, True)
            await asyncio.sleep(3)
            relay.set_state(1, False)`

Initial activation is fine, however it throws that particular error after the sleeping period.

As I say though at least re-finding the relay allows you to interact with it again, decent work around for the time being

**Comment by JPEWdev** [comment]
Hmm, this code works for me

```python
#! /usr/bin/env python3
import pyhid_usb_relay
import time

relay = pyhid_usb_relay.find()

relay.set_state(1, True)
time.sleep(3)
relay.set_state(1, False)
```

I'm wondering if this is some weird interaction with asyncio.... can you either provide the entire script or a minimal example that exhibits the problem?

**Comment by onurcanbaysal** [comment]
Hello,

`
import pyhid_usb_relay
import time

relay = pyhid_usb_relay.find()

relay.set_state(1, True)
time.sleep(3)
relay.set_state(1, False)
`
This code that you provided raises 

> raise USBError(errmsg, ret)
> usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed, win error: The I/O operation has been aborted because of either a thread exit or an application request.\r\n\n'

I am using windows 10.

**Comment by onurcanbaysal** [comment]
If you find the relay after each state change, then it works fine.
