### ISSUE TITLE
get-serial example?

### ISSUE THREAD

**Issue by ghost** [JPEWdev/pyhid-usb-relay#8]
Apologies if this is the wrong format, I never use GitHub,

I can see the subcommand get-serial for the relays given they all report the same ID however could I just get confirmation on how I'd run this within a .py itself?

For context, seems I'd just use relay.serial in this case (in my case returning "PERTH", seems the handler shortens the ID, however as I don't have a second relay to test I want to make sure this is the correct way to obtain the serial.

Thanks folks

**Comment by JPEWdev** [comment]
You are correct; `relay.serial` is how you can programmatically determine the serial number:
```python
import pyhid_usb_relay
relay = pyhid_usb_relay.find()
print(relay.serial)
```

Due to the way serial numbers are reported by the relays, they are restricted to 5 characters (+ a NUL terminator).
